//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySportsBook.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchCount
    {
        public int PK_BatchCount { get; set; }
        public int FK_VenueId { get; set; }
        public int FK_BatchId { get; set; }
        public int FK_CourtId { get; set; }
        public int Count { get; set; }
    
        public virtual Master_Batch Master_Batch { get; set; }
        public virtual Master_Court Master_Court { get; set; }
        public virtual Master_Venue Master_Venue { get; set; }
    }
}
