//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySportsBook.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCTransaction
    {
        public int ID { get; set; }
        public string TransactionDetail { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> Cost { get; set; }
    }
}
