//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySportsBook.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuration_StudioUser
    {
        public int PK_StudioUserId { get; set; }
        public string Name { get; set; }
        public int FK_StatusId { get; set; }
    
        public virtual Configuration_Status Configuration_Status { get; set; }
    }
}
