//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySportsBook.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuration_Screen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Configuration_Screen()
        {
            this.Master_VenueScreen = new HashSet<Master_VenueScreen>();
            this.Master_ScreenNumberFormat = new HashSet<Master_ScreenNumberFormat>();
        }
    
        public int PK_ScreenId { get; set; }
        public string Screen { get; set; }
        public string ScreenCode { get; set; }
        public string NavigationURL { get; set; }
        public string Area { get; set; }
        public string Controller { get; set; }
        public Nullable<int> FK_ScreenTypeId { get; set; }
        public string Action { get; set; }
    
        public virtual Configuration_ScreenType Configuration_ScreenType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Master_VenueScreen> Master_VenueScreen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Master_ScreenNumberFormat> Master_ScreenNumberFormat { get; set; }
    }
}
