//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySportsBook.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_SMS_Config
    {
        public int PK_SMSId { get; set; }
        public int FK_VenueId { get; set; }
        public string SMSCode { get; set; }
    
        public virtual Master_Venue Master_Venue { get; set; }
    }
}
