//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySportsBook.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_ExpenseType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Master_ExpenseType()
        {
            this.Transaction_Expense = new HashSet<Transaction_Expense>();
        }
    
        public int PK_ExpenseTypeId { get; set; }
        public int FK_VenueId { get; set; }
        public string ExpenseCode { get; set; }
        public string ExpenseDescription { get; set; }
    
        public virtual Master_Venue Master_Venue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction_Expense> Transaction_Expense { get; set; }
    }
}
