//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySportsBook.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MySportsBookEntities : DbContext
    {
        public MySportsBookEntities()
            : base("name=MySportsBookEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Configuration_BatchType> Configuration_BatchType { get; set; }
        public virtual DbSet<Configuration_Format> Configuration_Format { get; set; }
        public virtual DbSet<Configuration_InvoicePeriod> Configuration_InvoicePeriod { get; set; }
        public virtual DbSet<Configuration_PlayerType> Configuration_PlayerType { get; set; }
        public virtual DbSet<Configuration_Screen> Configuration_Screen { get; set; }
        public virtual DbSet<Configuration_Status> Configuration_Status { get; set; }
        public virtual DbSet<Configuration_User> Configuration_User { get; set; }
        public virtual DbSet<Confirguration_PaymentMode> Confirguration_PaymentMode { get; set; }
        public virtual DbSet<Master_BatchTiming> Master_BatchTiming { get; set; }
        public virtual DbSet<Master_CoachingLevel> Master_CoachingLevel { get; set; }
        public virtual DbSet<Master_Court> Master_Court { get; set; }
        public virtual DbSet<Master_Enquiry> Master_Enquiry { get; set; }
        public virtual DbSet<Master_Player> Master_Player { get; set; }
        public virtual DbSet<Master_Role> Master_Role { get; set; }
        public virtual DbSet<Master_RoleScreen> Master_RoleScreen { get; set; }
        public virtual DbSet<Master_ScreenNumberFormat> Master_ScreenNumberFormat { get; set; }
        public virtual DbSet<Master_Sport> Master_Sport { get; set; }
        public virtual DbSet<Master_UserRole> Master_UserRole { get; set; }
        public virtual DbSet<Master_UserVenue> Master_UserVenue { get; set; }
        public virtual DbSet<Master_Venue> Master_Venue { get; set; }
        public virtual DbSet<OtherBooking> OtherBookings { get; set; }
        public virtual DbSet<OtherBookingDetail> OtherBookingDetails { get; set; }
        public virtual DbSet<Transaction_Attendance> Transaction_Attendance { get; set; }
        public virtual DbSet<Transaction_Enquiry_Comments> Transaction_Enquiry_Comments { get; set; }
        public virtual DbSet<Transaction_PlayerSport> Transaction_PlayerSport { get; set; }
        public virtual DbSet<Transaction_Receipt> Transaction_Receipt { get; set; }
        public virtual DbSet<Transaction_Voucher> Transaction_Voucher { get; set; }
        public virtual DbSet<Master_Batch> Master_Batch { get; set; }
        public virtual DbSet<Transaction_Invoice> Transaction_Invoice { get; set; }
        public virtual DbSet<Transaction_InvoiceDetail> Transaction_InvoiceDetail { get; set; }
    }
}
