//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySportsBook.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherBookingDetail
    {
        public int PK_BookingDetailId { get; set; }
        public int FK_BookingId { get; set; }
        public int FK_VenueId { get; set; }
        public string Court { get; set; }
        public string Date { get; set; }
        public string Slot { get; set; }
        public string Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Configuration_User Configuration_User { get; set; }
        public virtual Configuration_User Configuration_User1 { get; set; }
        public virtual Master_Venue Master_Venue { get; set; }
        public virtual OtherBooking OtherBooking { get; set; }
    }
}
