//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySportsBook.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSTransactionRequest
    {
        public int SMSTransactionID { get; set; }
        public string SenderID { get; set; }
        public string PaymentBy { get; set; }
        public string PaymentMonth { get; set; }
        public string PaymentFor { get; set; }
        public string PaymentAmount { get; set; }
        public string MessageBody { get; set; }
        public string ReceipentNumber { get; set; }
        public string ReceiptNumber { get; set; }
        public Nullable<bool> IsSent { get; set; }
        public string ResponseString { get; set; }
        public string VenueName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Sport { get; set; }
        public string Batch { get; set; }
        public Nullable<int> SportID { get; set; }
        public Nullable<int> PlayerID { get; set; }
        public Nullable<int> BatchID { get; set; }
        public Nullable<int> VenueID { get; set; }
        public string Receiver { get; set; }
        public Nullable<int> ReceivedBy { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public Nullable<int> InvoiceDetailID { get; set; }
        public Nullable<int> PaymentModeID { get; set; }
        public string PaymentMode { get; set; }
    }
}
