//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySportsBook.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Studio_ExpenseType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Studio_ExpenseType()
        {
            this.Studio_ExpenseDetail = new HashSet<Studio_ExpenseDetail>();
        }
    
        public int PK_ExpenseTypeId { get; set; }
        public string ExpenseType { get; set; }
        public int FK_StatusId { get; set; }
    
        public virtual Configuration_Status Configuration_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Studio_ExpenseDetail> Studio_ExpenseDetail { get; set; }
    }
}
