//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySportsBook.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_Attendance
    {
        public int PK_AttendanceId { get; set; }
        public System.DateTime Date { get; set; }
        public int FK_VenueId { get; set; }
        public int FK_BatchId { get; set; }
        public int FK_PlayerId { get; set; }
        public bool Present { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Master_Batch Master_Batch { get; set; }
        public virtual Master_Player Master_Player { get; set; }
        public virtual Master_Venue Master_Venue { get; set; }
    }
}
