//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySportsBook.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_ReceiptDetail
    {
        public int PK_ReceiptDetailId { get; set; }
        public int FK_ReceiptId { get; set; }
        public int FK_InvoiceDetailId { get; set; }
        public decimal Amount { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
    
        public virtual Configuration_User Configuration_User { get; set; }
        public virtual Configuration_User Configuration_User1 { get; set; }
        public virtual Transaction_InvoiceDetail Transaction_InvoiceDetail { get; set; }
        public virtual Transaction_Receipt Transaction_Receipt { get; set; }
    }
}
