//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySportsBook.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_Voucher
    {
        public int PK_VoucherId { get; set; }
        public string VoucherNumber { get; set; }
        public System.DateTime VoucherDate { get; set; }
        public string PaymentFor { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> PaymentMode { get; set; }
        public string ReceivedBy { get; set; }
        public string Description { get; set; }
        public string TransactionNumer { get; set; }
        public int FK_StatusId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Configuration_Status Configuration_Status { get; set; }
        public virtual Configuration_User Configuration_User { get; set; }
        public virtual Configuration_User Configuration_User1 { get; set; }
    }
}
