//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySportsBook.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_PlayerSport
    {
        public int PK_PlayerSportId { get; set; }
        public int FK_VenueId { get; set; }
        public int FK_PlayerId { get; set; }
        public int FK_SportId { get; set; }
        public int FK_BatchId { get; set; }
        public int FK_CourtId { get; set; }
        public int FK_InvoicePeriodId { get; set; }
        public string LastGeneratedMonth { get; set; }
        public bool IsCoach { get; set; }
        public Nullable<int> FK_CoachingLevelId { get; set; }
        public int FK_StatusId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public decimal Fee { get; set; }
    
        public virtual Configuration_InvoicePeriod Configuration_InvoicePeriod { get; set; }
        public virtual Configuration_Status Configuration_Status { get; set; }
        public virtual Configuration_User Configuration_User { get; set; }
        public virtual Configuration_User Configuration_User1 { get; set; }
        public virtual Master_Batch Master_Batch { get; set; }
        public virtual Master_CoachingLevel Master_CoachingLevel { get; set; }
        public virtual Master_Court Master_Court { get; set; }
        public virtual Master_Player Master_Player { get; set; }
        public virtual Master_Sport Master_Sport { get; set; }
        public virtual Master_Venue Master_Venue { get; set; }
    }
}
