//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySportsBook.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_Receipt
    {
        public int PK_ReceiptId { get; set; }
        public string ReceiptNumber { get; set; }
        public System.DateTime ReceiptDate { get; set; }
        public int FK_VenueId { get; set; }
        public int FK_InvoiceId { get; set; }
        public decimal AmountPaid { get; set; }
        public string Description { get; set; }
        public int FK_PaymentModeId { get; set; }
        public string TransactionNumber { get; set; }
        public int FK_StatusId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public decimal TotalFee { get; set; }
        public Nullable<decimal> TotalOtherAmount { get; set; }
        public Nullable<decimal> TotalDiscountAmount { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<int> ReceivedBy { get; set; }
    
        public virtual Configuration_Status Configuration_Status { get; set; }
        public virtual Configuration_User Configuration_User { get; set; }
        public virtual Configuration_User Configuration_User1 { get; set; }
        public virtual Configuration_User Configuration_User2 { get; set; }
        public virtual Confirguration_PaymentMode Confirguration_PaymentMode { get; set; }
        public virtual Master_Venue Master_Venue { get; set; }
        public virtual Transaction_Invoice Transaction_Invoice { get; set; }
    }
}
