//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySportsBook.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaction_Invoice()
        {
            this.Transaction_InvoiceDetail = new HashSet<Transaction_InvoiceDetail>();
            this.Transaction_Receipt = new HashSet<Transaction_Receipt>();
        }
    
        public int PK_InvoiceId { get; set; }
        public string InvoiceNumber { get; set; }
        public int FK_VenueId { get; set; }
        public int FK_PlayerId { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public System.DateTime DueDate { get; set; }
        public decimal TotalFee { get; set; }
        public Nullable<decimal> TotalDiscount { get; set; }
        public Nullable<decimal> OtherAmount { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public string Comments { get; set; }
        public int FK_StatusId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Configuration_Status Configuration_Status { get; set; }
        public virtual Configuration_User Configuration_User { get; set; }
        public virtual Configuration_User Configuration_User1 { get; set; }
        public virtual Master_Player Master_Player { get; set; }
        public virtual Master_Venue Master_Venue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction_InvoiceDetail> Transaction_InvoiceDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction_Receipt> Transaction_Receipt { get; set; }
    }
}
