//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySportsBook.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PlayerSport
    {
        public int Player_PlayerId { get; set; }
        public int Player_VenueId { get; set; }
        public int Player_PlayerTypeId { get; set; }
        public string Player_FirstName { get; set; }
        public string Player_LastName { get; set; }
        public string Player_PlayerAddress { get; set; }
        public string Player_Email { get; set; }
        public string Player_Mobile { get; set; }
        public int Player_PlayerStatusId { get; set; }
        public Nullable<decimal> Player_PlayerCreditBalance { get; set; }
        public decimal Player_Fee { get; set; }
        public int Batch_BatchId { get; set; }
        public int Batch_VenueId { get; set; }
        public string Batch_BatchName { get; set; }
        public string Batch_BatchCode { get; set; }
        public int Batch_BatchCourtID { get; set; }
        public decimal Batch_Fee { get; set; }
        public int Sport_SportId { get; set; }
        public string Sport_SportName { get; set; }
        public string Sport_SportCode { get; set; }
        public int Sport_VenueId { get; set; }
        public decimal Sport_Fee { get; set; }
        public string Court_CourtCode { get; set; }
        public string Court_CourtName { get; set; }
    }
}
