//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySportsBook.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PlayerDetails
    {
        public int PlayerId { get; set; }
        public string PlayerName { get; set; }
        public string PlayerNameLastName { get; set; }
        public string Mobile { get; set; }
        public int VenueId { get; set; }
        public int SportID { get; set; }
        public string SportName { get; set; }
        public int BatchID { get; set; }
        public string BatchName { get; set; }
        public string BatchCode { get; set; }
        public int BatchType { get; set; }
        public Nullable<decimal> CreditBalance { get; set; }
        public int PlayerSportId { get; set; }
        public string LastGeneratedMonth { get; set; }
        public decimal PlayerFee { get; set; }
        public string SportCode { get; set; }
        public int PlayerStatusId { get; set; }
        public bool IsAttendanceRequired { get; set; }
    }
}
